Repository HarshS16/Civix, pull requests merged in 2025-08, with the labels that each got.

#411 Enhancement of Profile UI
  src/Pages/Profile.jsx
Labels: SSoC25, Advanced

#418 Enhancement of Term and Privacy Page
  src/Pages/Privacy.jsx
  src/Pages/Terms.jsx
Labels: SSoC25, Advanced

#429 Improved UI of iOS Page and implemented Dark Mode
  src/Pages/DownloadIOS.jsx
Labels: SSoC25, Advanced

#430 Improved UI of Android Page with Dark Mode Implementation.
  src/Pages/DownloadAndroid.jsx
Labels: SSoC25, Advanced

#434 Enhancement of File a Complaint Page
  src/Pages/ReportIssue.jsx
Labels: SSoC25, Advanced

#468 Improved UI of Testimonial Carousel
  src/components/TestimonialCarousel.jsx
Labels: SSoC25, Advanced

#470 FAQ stylings changed
  src/Home.jsx
Labels: SSoC25, Intermediate

#480 SOS page added
  src/App.jsx
  src/Pages/SOS.jsx
  src/components/Navbar.jsx
Labels: SSoC25, Advanced

#485 Improved Footer Section
  src/components/Footer.jsx
Labels: SSoC25, Intermediate

#497 Updated UI of SOS page
  src/Pages/SOS.jsx
  src/components/Navbar.jsx
Labels: SSoC25, Intermediate

#502 Enhnced the qrcode styling
  src/Home.jsx
  src/Pages/DownloadAndroid.jsx
  src/Pages/DownloadIOS.jsx
  src/components/DownloadPageQRCode.jsx
  src/components/EnhancedQRCode.css
  src/components/EnhancedQRCode.jsx
Labels: Intermediate, GSSOC

#510 Mobile responsive
  src/Pages/MyComplaints.jsx
Labels: Beginner, GSSOC

#513 Voting system implemented
  src/App.jsx
  src/Pages/VotingSystem.jsx
  src/components/Navbar.jsx
  src/components/voting/PollCreation.jsx
  src/components/voting/PollList.jsx
  src/components/voting/PollResults.jsx
  src/components/voting/PollVoting.jsx
Labels: Advanced, GSSOC

#522 Tax Impact Calculator Page added
  package-lock.json
  package.json
  src/App.jsx
  src/Pages/CivicEducation.jsx
  src/Pages/TaxImpact.jsx
Labels: SSoC25, Advanced

#523 Feat/improve navbar layout
  src/Home.css
  src/components/Navbar.jsx
Labels: Intermediate, GSSOC

#531 cleaned up profile routes
  backend/controllers/profileControllers.js
  backend/routes/profileRoutes.js
Labels: Advanced, GSSOC

#533 Voting page is now functional
  src/Pages/VotingSystem.jsx
Labels: SSoC25, Advanced

#536 issue #525 Add user feedback form on homepage
  src/components/Footer.jsx
  yarn.lock
Labels: SSoC25, Intermediate

#540 New Chatbot with enhanced Functionality and style Updated
  public/index.html
Labels: SSoC25, Advanced

#544 About Page UI Enhanced
  package-lock.json
  package.json
  src/Pages/About.css
  src/Pages/About.jsx
  src/assets/mission.png
  yarn.lock
Labels: SSoC25, Beginner

#551 cleaned up contributor routes
  backend/controllers/contributor.js
  backend/routes/contributions.js
Labels: Advanced, GSSOC

#564 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: Intermediate, GSSOC

#570 pr create automate message added
  .github/workflows/pr-create-automate-message.yml
Labels: Intermediate, GSSOC

#573 Notifications Page added in Admin Dashboard
  src/App.jsx
  src/Pages/Notification.jsx
  yarn.lock
Labels: SSoC25, Advanced

#577 Settings Page implemented in Admins Dashboard
  src/App.jsx
  src/Pages/Settings.jsx
Labels: SSoC25, Intermediate

#581 Dark Mode in Admin Dashboard
  src/components/AdminDashboard.jsx
Labels: SSoC25, Intermediate

#587 Dark Mode for Analytics Page
  src/Pages/Analytics.jsx
Labels: SSoC25, Intermediate

#588 Dark Mode in Users Page
  src/Pages/Users.jsx
Labels: SSoC25, Intermediate

#589 Dark Mode for Documents Page
  src/Pages/Documents.jsx
Labels: SSoC25, Intermediate

#591 Dark Mode for Settings Page
  src/Pages/Settings.jsx
Labels: SSoC25, Advanced

#592 fix: improve spacing between SOS, dark mode, and profile buttons
  package-lock.json
  src/components/Navbar.jsx
  yarn.lock
Labels: SSoC25, Beginner

#596 Nearby Service Feature Added
  src/App.jsx
  src/Pages/NearbyServices.jsx
  src/Pages/UserDashboard.jsx
Labels: SSoC25, Advanced

#600 Added a delete issue controller and its route
  backend/controllers/issues.js
  backend/routes/issues.js
Labels: Advanced, GSSOC

#602 Community Page Added to Dashboard
  .env
  .gitignore
  src/App.jsx
  src/Pages/CommunityHolidays.jsx
  src/Pages/UserDashboard.jsx
  yarn.lock
Labels: SSoC25, Intermediate

#608 Fix
  src/Pages/UserDashboard.jsx
Labels: SSoC25, Advanced

#609 feat:Add Custom Form Validation to Contact Form
  src/Pages/Contact.jsx
Labels: SSoC25, Advanced

#623 Transport Page Added
  package-lock.json
  package.json
  public/gtfs/stops.txt
  src/App.jsx
  src/Pages/Transport.jsx
  src/Pages/UserDashboard.jsx
  yarn.lock
Labels: SSoC25, Intermediate

#626 Implementation of Modular Election Information Card within Dashboard Architecture
  public/gtfs/elections.json
  public/gtfs/voters.csv
  src/App.jsx
  src/Pages/Election.jsx
  src/Pages/UserDashboard.jsx
Labels: SSoC25, Intermediate

#627 Integration of Government Schemes Page within Dashboard Ecosystem
  public/gtfs/planExpenditure.csv
  public/gtfs/schemes.csv
  src/App.jsx
  src/Pages/Schemes.jsx
  src/Pages/UserDashboard.jsx
Labels: SSoC25, Advanced

#628 Added Vehicles Management Module with External RC & Traffic Fine Links
  src/App.jsx
  src/Pages/UserDashboard.jsx
  src/Pages/Vehical.jsx
Labels: SSoC25, Intermediate

#632 terms ui
  src/Pages/Terms.jsx
Labels: SSoC25, Intermediate

#655 Userprofilevalidation
  src/Pages/About.jsx
  src/Pages/Profile.jsx
Labels: SSoC25, Advanced

#701 Integration of Aviation Services Orchestration Layer via Air Seva Module into Civix Dashboard with Dynamic Data Hydration and Modular Rendering Architecture
  public/gtfs/93710e81-db2b-4f95-9223-89156dfd8bc9.csv
  src/App.jsx
  src/Pages/AirSeva.jsx
  src/Pages/UserDashboard.jsx
Labels: SSoC25, Advanced

#707 Feat: Add Custom JS Validation & Signup Redirect Link on Login Page
  src/components/Auth.css
  src/components/Login.jsx
Labels: Advanced, gssoc25

#755 Deployment of a Viewport-Adaptive Navigation Orchestration Pipeline for Admin Dashboard via Sidebar-to-Collapsible Menu Transformation
  src/Pages/AdminDashboard.jsx
Labels: SSoC25, Advanced

#747 Deployment of Adaptive Navigation Schema for Enhanced Responsiveness in Documents Page via Context-Aware Menu Substitution on Constrained Viewports
  src/Pages/Documents.jsx
Labels: SSoC25, Advanced

#728 Adaptive Photometric Rendering Pipeline for Train Schedule Interface via Dark Mode Integration
  src/Pages/Train.jsx
Labels: SSoC25, Advanced

#733 Implementation of High-Fidelity CSV-Driven ETL & Visualization Framework for Nationwide School Data in Civix
  public/gtfs/UDISE_2021_22_Table_7.11.csv
  src/App.jsx
  src/Pages/School.jsx
  src/Pages/UserDashboard.jsx
Labels: SSoC25, Advanced

#737 Nearbyservicesui
  src/Pages/CommunityVotingPage.jsx
  src/Pages/NearbyServices.jsx
Labels: SSoC25, Intermediate

#761 Implements advanced data visualizations and interactive analytics for the Elections Info dashboard
  src/Pages/Election.jsx
Labels: SSoC25, Advanced

#734 Deployment of an Indexed Search and Retrieval Subsystem within the User Dashboard
  src/Pages/UserDashboard.jsx
Labels: SSoC25, Advanced

#764 Resolve Fatal Rendering Pipeline Failure in Community Voting Module
  package-lock.json
  src/Pages/AirSeva.jsx
  src/Pages/CommunityVotingPage.jsx
  yarn.lock
Labels: SSoC25, Advanced

#767 Enhanced Feedback system
  src/Pages/Feedback.jsx
  src/Pages/VotingSystem.jsx
  src/components/Footer.jsx
  src/components/voting/VotingFeedbackModal.jsx
Labels: Intermediate, gssoc25

#773 Deployment of Geospatial UI Rendering Overhaul for User Map Module
  src/Pages/UserMap.jsx
Labels: SSoC25, Advanced

#775 Implmentation of Profile Setup Module with Adaptive Breakpoints, Context-Driven Form Logic, and Deterministic Rendering Pipeline
  src/Pages/ProfileSetup.jsx
Labels: SSoC25, Advanced

#779 Deployment of deterministic and Adaptive My Complains Page with Context-Driven State Management and GPU-Accelerated Interaction Pipeline
  src/Pages/MyComplaints.jsx
Labels: SSoC25, Advanced

#801 Deployment of High-Throughput Virtual DOM Diffing and Concurrent UI Composition for Contact Us Module
  src/Pages/Contact.jsx
Labels: SSoC25, Advanced

#802 Deployment of deterministic & Adaptive UI Overhaul of Resources Page with Optimized Rendering Stack
  src/Pages/Resources.jsx
Labels: SSoC25, Advanced

#804 Deployment of UI Overhaul of Nearby Service for High-Precision Rendering and Improved Usability
  src/Pages/NearbyServices.jsx
Labels: SSoC25, Advanced

#805 Deployment of Next-Generation UI Modernization for Lost and Found Module with Modular Component Architecture
  src/Pages/Lost&Found.jsx
Labels: SSoC25, Advanced

#807 Deployment of High-Fidelity UI Overhaul for Public Transport with Progressive Rendering, Atomic Component Architecture, and Real-Time Data Hydration
  src/Pages/Transport.jsx
Labels: SSoC25, Advanced

#808 Deployment of Performance-Centric Redesign of Civic Stats Module Leveraging Modular Architecture and GPU-Optimized Interaction and Visualization Pipeline
  src/Pages/CivicStatistics.jsx
Labels: SSoC25, Advanced

#795 FIX #748: fix cutoff heading in privacy page
  src/Pages/Privacy.jsx
Labels: SSoC25, Beginner

#815 Deployment of Scalable and Responsive Interface for Real-Time Train Schedule with Dynamic Interaction Pipeline and Latency-Optimized Rendering
  src/Pages/Train.jsx
Labels: SSoC25, Advanced

#818 Deployment of Performance-Centric Redesign of Admin Dashboard with Modular Architecture and GPU-Optimized Interaction and Visualization Pipeline
  src/Pages/AdminDashboard.jsx
Labels: SSoC25, Advanced

#822 Deployment of Performance-Centric Redesign of Admin Users Dashboard with Modular Architecture and GPU-Accelerated Interaction and Visualization Pipeline
  src/Pages/Users.jsx
Labels: SSoC25, Advanced

#777 Deployment of deterministic and Adaptive File a Complaint Page with Context-Driven Form Management and GPU-Accelerated Interaction Pipeline
  src/Pages/ReportIssue.jsx
Labels: SSoC25, Advanced

#810 Deployment of Performance-Centric Redesign of Traffic Fines & Vehicle Info Page with Modular Architecture and GPU-Optimized Interaction and Visualization Pipeline
  src/Pages/Vehical.jsx
Labels: SSoC25, Advanced

#813 Deployment of Performance-Centric Redesign of Air Seva Page with Modular Architecture and GPU-Optimized Interaction and Visualization Pipeline
  src/Pages/AirSeva.jsx
Labels: SSoC25, Advanced

#829 Deployment of Architectural Revamp of Community Voting Interface with Dynamic Rendering and State Synchronization
  src/Pages/CommunityVotingPage.jsx
Labels: SSoC25, Advanced

#833 Deployed Revamp UI/UX of Contact Us Page for Enhanced Interaction and Accessibility
  src/Pages/Contact.jsx
Labels: SSoC25, Advanced

#838 Deployment of High-Performance, Responsive UI Redesign for Contributors Page with Modular Layout and GPU-Optimized Rendering
  src/Pages/Contributors.jsx
Labels: SSoC25, Advanced

#840 Deployment of Adaptive, High-Performance UI Architecture for SOS Page with Optimized Rendering and Enhanced UX Patterns
  src/Pages/SOS.jsx
Labels: SSoC25, Advanced

#842 Deployment of Scalable, High-Performance UI Enhancements for My Complaints Page with Modular Design & Optimized UX Flow
  src/Pages/MyComplaints.jsx
Labels: SSoC25, Advanced

#844 Deployment of Modular and High-Performance UI Enhancement for Resources Page with Optimized Layout, Accessibility & Dynamic Rendering
  src/Pages/Resources.jsx
Labels: SSoC25, Advanced

#846 Deployment of High-Performance UI Enhancement for Lost and Found Page with Optimized Navigation & Interactive Components
  src/Pages/Lost&Found.jsx
Labels: SSoC25, Advanced

#848 Deployment of Advanced UI Revamp of Vehicle and Fine Page with Optimized Data Visualization & Responsive Layout
  src/Pages/Vehical.jsx
Labels: SSoC25, Advanced

#850 Deployment of UI Enhancement of Community Holidays Page with Optimized Layout and Interactive Components
  src/Pages/CommunityHolidays.jsx
Labels: SSoC25, Advanced

#852 Deployment of Enhanced UI of Electricity and Water Outage Page with Interactive Status Indicators and Optimized Layout
  src/Pages/Electricity.jsx
Labels: SSoC25, Advanced

#854 Deployment of Advanced UI Enhancement of Budget Page with Optimized Data Visualization & Interactive Controls
  src/Pages/Budget.jsx
Labels: SSoC25, Advanced
